algoritmo "Exemplo 9.1 - Cálculo de média aritmética"
//Exemplo 9.1 do material "Introdução aos algoritmos" do NAPRO-UCS
var
   A, B, Media: REAL
inicio
   Escreval ("Cálculo da média aritmética entre dois valores")
   Escreva ("Digite o primeiro valor: ")
   Leia (A)
   Escreva ("Digite o segundo valor: ")
   Leia (B)
   Media <- (A+B)/2
   Escreval ("A média aritmética entre os dois valores é:", Media)
fimalgoritmo